Update iOS SDK documentation.
SwedbankPay/developer.swedbankpay.com pull request #1128
Opened 2021-08-25 08:45 UTC by IhmeHippi

iOS SDK now supports SwiftPM. Added instructions for installation through SwiftPM.

2021-08-25 08:54 UTC, asbjornu requested changes

2021-08-25 08:54 UTC, asbjornu commented on modules-sdks/mobile-sdk/ios.md
>  [cocoapods-gettingstarted]: https://guides.cocoapods.org/using/getting-started.html
Seems like some of these link references are no longer in use?

```
modules-sdks/mobile-sdk/ios.md
  456:1-456:84  warning  Found unused definition  no-unused-definitions  remark-lint
  457:1-457:75  warning  Found unused definition  no-unused-definitions  remark-lint
```

2021-09-01 07:42 UTC, asbjornu approved these changes

2021-09-01 07:44 UTC, asbjornu commented
This is weird. GitHub thinks the PR is out of date, but I can't update it?

<img width="429" alt="image" src="https://user-images.githubusercontent.com/12283/131632473-141502a4-d1c1-4566-950d-632349e2a89a.png">

2021-09-01 07:45 UTC, IhmeHippi commented
Should I manually rebase it against develop and force push?

2021-09-01 08:01 UTC, asbjornu commented
Yes, please do.

2021-09-01 09:22 UTC, IhmeHippi commented
Rebased

2021-09-01 10:09 UTC, merged