DX-1637: Adding text for Set Up and Get Started
SwedbankPay/developer.swedbankpay.com pull request #1260
Opened 2021-11-29 01:19 UTC by arebra

Visually appalling as the design isn't in place with the boxes.

The text misses an example that I guess will need a screenshot.

The main index page went completely FUBAR when I tried goofing around with the boxes. I left it unchanged to not send everything down the toilet.

Merchant managed is missing it's set up page as it isn't included in this branch. Will add when MM is approved and merged.

2021-11-30 01:40 UTC, arebra commented
Jeg kan ikke for bare livet forstå hvorfor setup-sidene tryner. Jeg fikset til og med slik at det funket, men så tryner det igjen. Jeg holder på å tilte.

2021-11-30 10:12 UTC, asbjornu requested changes

2021-11-30 10:12 UTC, asbjornu commented on checkout/v3/index.md
> +**Standard**
remark-lint is reacting to this line where emphasis is being used instead of a heading. 

```suggestion
### Standard
```

2021-11-30 10:12 UTC, asbjornu commented on checkout/v3/index.md
> +**Authenticated**
remark-lint is reacting to this line where emphasis is being used instead of a heading. 

```suggestion
### Authenticated
```

2021-11-30 10:12 UTC, asbjornu commented on checkout/v3/index.md
> +**Merchant Authenticated Consumer**
remark-lint is reacting to this line where emphasis is being used instead of a heading. 

```suggestion
### Merchant Authenticated Consumer
```

2021-11-30 10:12 UTC, asbjornu commented on checkout/v3/index.md
> +**Payments**
remark-lint is reacting to this line where emphasis is being used instead of a heading. 

```suggestion
### Payments
```

2021-11-30 12:55 UTC, asbjornu requested changes
```

2021-11-30 13:54 UTC, asbjornu commented
Remove the trailing slash from the links and they should work. 😃 I hope the below table explains the issue in more detail.

| Resulting link | Implied source file | Exists |
| :-------------- | :------------------ | :---: |
| `/checkout/v3/authenticated/setup/` | `/checkout/v3/authenticated/setup/index.md` | ❌ |
| `/checkout/v3/authenticated/setup` | `/checkout/v3/authenticated/setup.md` | ✅ |

2021-11-30 14:50 UTC, arebra commented
Doing the above resulted in four blank pages :(

2021-12-01 13:38 UTC, arebra commented
Trieu tried the branch locally and the setup links worked for him.

2021-12-01 13:55 UTC, asbjornu approved these changes
LGTM! 🚀

2021-12-01 21:59 UTC, merged