Feature/dx 1702 update about text for checkoutv3 implementations
SwedbankPay/developer.swedbankpay.com pull request #1373
Opened 2022-01-28 12:41 UTC by trieutran91

Update with text from https://www.figma.com/file/Ys5zmsVCmYt3yL4DruLzj0/FrontPage-V3-Entry?node-id=1199%3A69106

2022-01-28 12:54 UTC, trieutran91 commented
This branch is actually based on #1364. Which will avoid the need for rebase?

2022-01-28 13:07 UTC, asbjornu commented
It's going to make a rebase simpler, but the merge-commit of #1364 is going to move `develop` ahead so it will have to be merged into this PR, or this PR will have to be rebased on `develop`. I prefer the latter (rebase).

2022-01-28 13:10 UTC, trieutran91 commented
> It's going to make a rebase simpler, but the merge-commit of #1364 is going to move `develop` ahead so it will have to be merged into this PR, or this PR will have to be rebased on `develop`. I prefer the latter (rebase).

Noted! Rebase it is :)

2022-02-02 14:57 UTC, arebra requested changes
The language geek back at it.

2022-02-02 14:57 UTC, arebra commented on checkout-v3/index.md
> +both consumer identification and payment menu) - meaning the consumer self can
```suggestion
both consumer identification and payment menu) - meaning the payer themself can
```

2022-02-02 14:57 UTC, arebra commented on checkout-v3/index.md
> +-   **Payer Info:** The consumers’ personal data e.g. name, address, card number
```suggestion
-   **Payer Info:** The payer’s personal data e.g. name, address, card number
```

2022-02-02 14:57 UTC, arebra commented on checkout-v3/index.md
> +-   **PSP:** The service of providing payment methods in the checkout.
```suggestion
-   **PSP:** The service of providing payment instruments in the checkout.
```

2022-02-02 14:57 UTC, arebra commented on checkout-v3/index.md
> +of payment methods and features to cater for your business needs.
```suggestion
of payment instruments and features to cater for your business needs.
```

2022-02-02 14:57 UTC, arebra commented on checkout-v3/index.md
> +From the **Full Checkout**, you will get access to a number of payment methods
```suggestion
From the **Full Checkout**, you will get access to a number of payment instruments.
```

2022-02-02 14:57 UTC, arebra commented on checkout-v3/index.md
> +safely store the consumers' data. And if the consumer agrees, we will store
```suggestion
safely store the payer's data. And if the payer agrees, we will store
```

2022-02-02 14:57 UTC, arebra commented on checkout-v3/index.md
> +their information to have it prefilled next time they shop.
```suggestion
their information to have it prefilled the next time they shop.
```

2022-02-02 14:57 UTC, arebra commented on checkout-v3/index.md
> +  text='The ultimate implementation pack for anyone new to this, needing support
```suggestion
  text='The ultimate implementation pack for anyone new to this, who needs support
```

2022-02-02 14:57 UTC, arebra commented on checkout-v3/index.md
> +  with all parts covering the checkout. We collect and verify the consumer
```suggestion
  with all parts covering the checkout. We collect and verify the payer's
```

2022-02-02 14:57 UTC, arebra commented on checkout-v3/index.md
> +  identity, the billing and shipping address and store the consumer data.
```suggestion
  identity, billing and shipping address, and store the payer data.
```

2022-02-02 14:57 UTC, arebra commented on checkout-v3/index.md
> +  authenticate and store the consumer data you collected? We got you covered and
```suggestion
  authenticate and store the payer data you collected? We've got you covered, so the
```

2022-02-02 14:57 UTC, arebra commented on checkout-v3/index.md
> +  text="If you only need support with data storage and payment methods - this is
```suggestion
  text="If you only need support with data storage and payment instruments - this is
```

2022-02-02 14:57 UTC, arebra commented on checkout-v3/index.md
> +  the consumer doesn’t need to fill out their information twice. Simply
```suggestion
payer won't have to fill out their information twice. Simply
```

2022-02-02 14:57 UTC, arebra commented on checkout-v3/index.md
> +With our payments only package, you collect the consumer data and have the
```suggestion
With our payments only package, you collect the payer data and have the
```

2022-02-02 14:57 UTC, arebra commented on checkout-v3/index.md
> +full range of payment methods.
```suggestion
full range of payment instruments.
```

2022-02-02 14:57 UTC, arebra commented on checkout-v3/index.md
> +  text="If you can collect, verify and store your consumer data, and if needed -
```suggestion
  text="If you can collect, verify and store your payer data, and if needed -
```

2022-02-02 14:57 UTC, arebra commented on checkout-v3/index.md
> +  if you want to offer a single payment method or the full payment offering. "
```suggestion
  if you want to offer a single payment instrument or the full payment offering."
```

2022-02-02 14:57 UTC, arebra commented on index.md
> +    Here you'll find the full toolbox for how to integrate our payment solutions and acquaint yourself with their different features and functionalities and learn how to integrate them.
```suggestion
    Here you'll find the full toolbox for how to integrate our payment solutions, acquaint yourself with their different features and functionalities, and learn how to integrate them.
```

2022-02-03 13:12 UTC, arebra requested changes
I missed a couple!

2022-02-03 13:12 UTC, arebra commented on checkout-v3/index.md
> +Here, you can choose from two main
```suggestion
Here, you can choose between two main
```

2022-02-03 13:12 UTC, arebra commented on checkout-v3/index.md
> +both consumer identification and payment menu) - meaning the payer themself can
```suggestion
both payer identification and payment menu) - meaning the payer themselves can
```

2022-02-03 13:12 UTC, arebra commented on checkout-v3/index.md
> +only. This means that you are in charge of collecting and storing the consumer
```suggestion
only. This means that you are in charge of collecting and storing the payer
```

2022-02-03 13:12 UTC, arebra commented on checkout-v3/index.md
> +data and the payment methods to be presented.
```suggestion
data and the payment instruments to be presented.
```

2022-02-03 14:37 UTC, arebra reviewed
Great :D

2022-02-03 14:38 UTC, arebra approved these changes
Wrong radio button :)

2022-02-03 14:49 UTC, asbjornu approved these changes

2022-02-03 14:50 UTC, merged