DX-2020: Add Click to Pay
SwedbankPay/developer.swedbankpay.com pull request #1690
Opened 2023-01-20 11:47 UTC by arebra

Added mentions of click to pay in text and paid response in  v3 resource and status models.

2023-01-20 16:29 UTC, asbjornu requested changes
Some wrinkles with the indentation, otherwise 👍🏼

2023-01-20 16:29 UTC, asbjornu commented on _includes/checkout-v3-status-models.md
> + ```
````suggestion
```http
HTTP/1.1 200 OK
Content-Type: application/json
{
  "paymentOrder": "/psp/paymentorders/5adc265f-f87f-4313-577e-08d3dca1a26c",
  "paid": {
    "id": "/psp/paymentorders/1f8d409e-8d8c-4ba1-a3ab-08da8caf7918/paid",
    "instrument": "ClickToPay",
    "number": 80100001190,
    "payeeReference": "1662360210",
    "amount": 1500,
    "details": {
      "nonPaymentToken": "12345678-1234-1234-1234-1234567890AB",
      "externalNonPaymentToken": "1234567890",
      "cardBrand": "Visa",
      "cardType": "Credit",
      "expiryDate": "12/0023",
      "issuerAuthorizationApprovalCode": "L00392",
      "acquirerTransactionType": "WALLET",
      "acquirerStan": "392",
      "acquirerTerminalId": "80100001190",
      "acquirerTransactionTime": "2022-09-05T06:45:40.322Z",
      "transactionInitiator": "CARDHOLDER"
      "bin": "489537"
    }
  }
}
```
````

2023-01-20 23:31 UTC, asbjornu requested changes
Sorry, I forgot this required newline in the previous review.

2023-01-20 23:31 UTC, asbjornu commented on _includes/checkout-v3-resource-models.md
> +{
```suggestion
Content-Type: application/json

{
```

2023-01-20 23:31 UTC, asbjornu commented on _includes/checkout-v3-status-models.md
> +{
```suggestion
Content-Type: application/json

{
```

2023-01-23 14:54 UTC, asbjornu approved these changes

2023-01-29 21:15 UTC, asbjornu commented on checkout-v3/index.md
> +[c2p-logo]: /assets/img/clicktopay-logo.svg
Does `/assets/img/clicktopay-logo.svg` already exist or did you forget to add it in this PR?

2023-02-23 13:48 UTC, closed without merging

2023-02-23 13:48 UTC, arebra commented
Added in Google Pay branch