new sideboard and theme
SwedbankPay/developer.swedbankpay.com pull request #618
Opened 2020-08-12 12:45 UTC by NullableInt

2020-08-12 12:48 UTC, payex-dev commented on Gemfile.lock
> +    rack (1.6.13)
Codacy found an issue: [Directory traversal in Rack::Directory app bundled with Rack (CVE-2020-8161)](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-08-12 12:48 UTC, payex-dev commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908&bid=19679799)

2020-08-13 10:56 UTC, payex-dev commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 18
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908&bid=19679799)

2020-08-13 12:36 UTC, payex-dev commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 18
- Added 3
           

Complexity increasing per file
==============================
- _plugins/sidebar.rb  12
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908&bid=19679799)

2020-08-13 12:36 UTC, payex-dev commented on _plugins/sidebar.rb
> +    def render(filename)
Codacy found an issue: [Cyclomatic complexity for render is too high. [7/6]](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-08-13 12:36 UTC, payex-dev commented on _plugins/sidebar.rb
> +    def generateSubgroup(filename, key, value, all_subgroups, level)
Codacy found an issue: [Cyclomatic complexity for generateSubgroup is too high. [12/6]](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-08-13 12:36 UTC, payex-dev commented on _plugins/sidebar.rb
> +    def generateSubgroup(filename, key, value, all_subgroups, level)
Codacy found an issue: [Perceived complexity for generateSubgroup is too high. [16/7]](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-08-24 06:27 UTC, payex-dev commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 18
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908&bid=19679799)

2020-08-31 05:42 UTC, payex-dev commented on payments/trustly/seamless-view.md
> +    activate Merchant
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-08-31 05:42 UTC, payex-dev commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 18
- Added 7
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908&bid=19679799)

2020-08-31 05:42 UTC, payex-dev commented on payments/trustly/seamless-view.md
> +    note left of Consumer: Open iframe ③
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-08-31 05:42 UTC, payex-dev commented on payments/trustly/seamless-view.md
> +    Consumer->>-SwedbankPay: Confirm purchase
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-08-31 05:42 UTC, payex-dev commented on payments/trustly/seamless-view.md
> +    activate Merchant
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-08-31 05:42 UTC, payex-dev commented on payments/trustly/seamless-view.md
> +    SwedbankPay-->>-Merchant: rel: view-authorization
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-08-31 05:42 UTC, payex-dev commented on payments/trustly/seamless-view.md
> +    Merchant-->>-Consumer: Display all details and final price
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-08-31 05:42 UTC, payex-dev commented on payments/trustly/seamless-view.md
> +    SwedbankPay->>-Trustly: Perform payment
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-09-02 21:01 UTC, payex-dev commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 18
- Added 7
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908&bid=19679799)

2020-09-02 21:01 UTC, payex-dev commented on payments/trustly/seamless-view.md
> +    activate Merchant
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-09-02 21:01 UTC, payex-dev commented on payments/trustly/seamless-view.md
> +    Consumer->>-SwedbankPay: Confirm purchase
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-09-02 21:01 UTC, payex-dev commented on payments/trustly/seamless-view.md
> +    SwedbankPay->>-Trustly: Perform payment
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-09-02 21:01 UTC, payex-dev commented on payments/trustly/seamless-view.md
> +    Merchant-->>-Consumer: Display all details and final price
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-09-02 21:01 UTC, payex-dev commented on payments/trustly/seamless-view.md
> +    SwedbankPay-->>-Merchant: rel: view-authorization
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-09-02 21:01 UTC, payex-dev commented on payments/trustly/seamless-view.md
> +    activate Merchant
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-09-02 21:01 UTC, payex-dev commented on payments/trustly/seamless-view.md
> +    note left of Consumer: Open iframe ③
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-09-03 10:49 UTC, payex-dev commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 18
- Added 7
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908&bid=19679799)

2020-09-03 10:49 UTC, payex-dev commented on payments/trustly/seamless-view.md
> +    Consumer->>-SwedbankPay: Confirm purchase
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-09-03 10:49 UTC, payex-dev commented on payments/trustly/seamless-view.md
> +    activate Merchant
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-09-03 10:49 UTC, payex-dev commented on payments/trustly/seamless-view.md
> +    SwedbankPay->>-Trustly: Perform payment
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-09-03 10:49 UTC, payex-dev commented on payments/trustly/seamless-view.md
> +    SwedbankPay-->>-Merchant: rel: view-authorization
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-09-03 10:49 UTC, payex-dev commented on payments/trustly/seamless-view.md
> +    Merchant-->>-Consumer: Display all details and final price
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-09-03 10:49 UTC, payex-dev commented on payments/trustly/seamless-view.md
> +    activate Merchant
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-09-03 11:10 UTC, payex-dev commented on payments/trustly/seamless-view.md
> +    SwedbankPay-->>-Merchant: rel: view-authorization
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-09-03 11:10 UTC, payex-dev commented on payments/trustly/seamless-view.md
> +    Consumer->>-SwedbankPay: Confirm purchase
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-09-03 11:10 UTC, payex-dev commented on payments/trustly/seamless-view.md
> +    note left of Consumer: Open iframe ③
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-09-03 11:10 UTC, payex-dev commented on payments/trustly/seamless-view.md
> +    activate Merchant
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-09-03 11:10 UTC, payex-dev commented on payments/trustly/seamless-view.md
> +    SwedbankPay->>-Trustly: Perform payment
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-09-03 11:10 UTC, payex-dev commented on payments/trustly/seamless-view.md
> +    activate Merchant
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-09-03 11:31 UTC, payex-dev commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 18
- Added 7
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908&bid=19679799)

2020-09-03 11:31 UTC, payex-dev commented on payments/trustly/seamless-view.md
> +    SwedbankPay-->>-Merchant: rel: view-authorization
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-09-03 11:31 UTC, payex-dev commented on payments/trustly/seamless-view.md
> +    note left of Consumer: Open iframe ③
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-09-03 11:31 UTC, payex-dev commented on payments/trustly/seamless-view.md
> +    Merchant-->>-Consumer: Display all details and final price
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-09-03 11:31 UTC, payex-dev commented on payments/trustly/seamless-view.md
> +    activate Merchant
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-09-03 11:31 UTC, payex-dev commented on payments/trustly/seamless-view.md
> +    SwedbankPay->>-Trustly: Perform payment
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-09-03 11:31 UTC, payex-dev commented on payments/trustly/seamless-view.md
> +    Consumer->>-SwedbankPay: Confirm purchase
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-09-03 11:31 UTC, payex-dev commented on payments/trustly/seamless-view.md
> +    activate Merchant
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-09-03 11:35 UTC, payex-dev commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 18
- Added 7
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908&bid=19679799)

2020-09-03 11:35 UTC, payex-dev commented on payments/trustly/seamless-view.md
> +    Consumer->>-SwedbankPay: Confirm purchase
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-09-03 11:35 UTC, payex-dev commented on payments/trustly/seamless-view.md
> +    activate Merchant
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-09-03 11:35 UTC, payex-dev commented on payments/trustly/seamless-view.md
> +    activate Merchant
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-09-03 11:35 UTC, payex-dev commented on payments/trustly/seamless-view.md
> +    SwedbankPay-->>-Merchant: rel: view-authorization
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-09-03 11:35 UTC, payex-dev commented on payments/trustly/seamless-view.md
> +    note left of Consumer: Open iframe ③
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-09-03 11:35 UTC, payex-dev commented on payments/trustly/seamless-view.md
> +    Merchant-->>-Consumer: Display all details and final price
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-09-03 11:35 UTC, payex-dev commented on payments/trustly/seamless-view.md
> +    SwedbankPay->>-Trustly: Perform payment
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-09-04 05:12 UTC, payex-dev commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 18
- Added 7
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908&bid=19679799)

2020-09-04 05:12 UTC, payex-dev commented on payments/trustly/seamless-view.md
> +    SwedbankPay-->>-Merchant: rel: view-authorization
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-09-04 05:12 UTC, payex-dev commented on payments/trustly/seamless-view.md
> +    note left of Consumer: Open iframe ③
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-09-04 05:12 UTC, payex-dev commented on payments/trustly/seamless-view.md
> +    Merchant-->>-Consumer: Display all details and final price
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-09-04 05:12 UTC, payex-dev commented on payments/trustly/seamless-view.md
> +    activate Merchant
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-09-04 05:12 UTC, payex-dev commented on payments/trustly/seamless-view.md
> +    activate Merchant
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-09-04 05:12 UTC, payex-dev commented on payments/trustly/seamless-view.md
> +    SwedbankPay->>-Trustly: Perform payment
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-09-04 05:12 UTC, payex-dev commented on payments/trustly/seamless-view.md
> +    Consumer->>-SwedbankPay: Confirm purchase
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908)

2020-09-04 05:59 UTC, marinafrydenb approved these changes
Amazing! im so exited!

2020-09-04 07:58 UTC, payex-dev commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 18
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908&bid=19679799)

2020-09-07 08:51 UTC, asbjornu approved these changes
Whoop! 🎉

2020-09-07 11:06 UTC, payex-dev commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 18
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908&bid=19679799)

2020-09-07 11:24 UTC, payex-dev commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 18
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908&bid=19679799)

2020-09-07 11:27 UTC, payex-dev commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 18
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908&bid=19679799)

2020-09-07 11:50 UTC, payex-dev commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 18
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908&bid=19679799)

2020-09-07 15:09 UTC, payex-dev commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 18
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908&bid=19679799)

2020-09-07 15:21 UTC, payex-dev commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 18
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908&bid=19679799)

2020-09-07 15:23 UTC, payex-dev commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 18
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908&bid=19679799)

2020-09-08 11:05 UTC, payex-dev commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 18
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908&bid=19679799)

2020-09-08 11:08 UTC, payex-dev commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 18
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908&bid=19679799)

2020-09-08 11:20 UTC, payex-dev commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 18
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908&bid=19679799)

2020-09-08 11:43 UTC, payex-dev commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 18
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908&bid=19679799)

2020-09-08 12:59 UTC, payex-dev commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 18
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908&bid=19679799)

2020-09-08 13:15 UTC, payex-dev commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 18
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908&bid=19679799)

2020-09-08 13:22 UTC, payex-dev commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 18
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908&bid=19679799)

2020-09-08 13:48 UTC, payex-dev commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 18
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908&bid=19679799)

2020-09-08 13:50 UTC, payex-dev commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 18
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908&bid=19679799)

2020-09-08 13:50 UTC, asbjornu requested changes

2020-09-08 13:50 UTC, asbjornu commented on .github/workflows/test.yml
> +      - name: Login docker
```suggestion
      - name: docker login
```

2020-09-08 13:50 UTC, asbjornu commented on .github/workflows/test.yml
> +          docker login https://docker.pkg.github.com -u SwedbankPay --password ${{ secrets.GITHUB_TOKEN }}
```suggestion
        run: docker login https://docker.pkg.github.com -u SwedbankPay --password ${{ secrets.GITHUB_TOKEN }}
```

2020-09-08 13:50 UTC, asbjornu commented on .github/workflows/test.yml
> +          docker login https://docker.pkg.github.com -u SwedbankPay --password ${{ secrets.GITHUB_TOKEN }}
```suggestion
      - name: docker login
        run: docker login https://docker.pkg.github.com -u SwedbankPay --password ${{ secrets.GITHUB_TOKEN }}
```

2020-09-08 14:25 UTC, payex-dev commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 18
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6002908&bid=19679799)

2020-09-08 15:06 UTC, asbjornu approved these changes

2020-09-08 15:50 UTC, merged