Feature/dx 976 logourl
SwedbankPay/developer.swedbankpay.com pull request #624
Opened 2020-08-19 12:56 UTC by marinafrydenb

2020-08-19 13:03 UTC, asbjornu requested changes
There should be some screenshots as well, no?

2020-08-19 13:03 UTC, asbjornu commented on _includes/payment-order-purchase.md
> +| {% icon check %} | └─➔&nbsp;`logoUrl`      | `string`     | If the configuration is activated and you send in a `logoUrl`, then the Swedbank pay logo is replaced with the logo sent in. If you do no
```suggestion
| {% icon check %} | └─➔&nbsp;`logoUrl`      | `string`     | With permission and activation on your contract, sending in a `logoUrl` will replace the Swedbank Pay logo with the logo sent in. If you do not send in a `logoUrl`, then no logo and no text is shown. Without permission or activation on your contract, sending in a `logoUrl` has no effect.                          |
```

2020-08-25 11:31 UTC, asbjornu approved these changes

2020-08-27 08:35 UTC, payex-dev commented on _includes/payment-order-other-features.md
> +[swapped-logo-payment]: /assets/screenshots/logourl/logourl-swapped.png
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6039190)

2020-08-27 08:35 UTC, payex-dev commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6039190&bid=19788691)

2020-08-27 08:35 UTC, payex-dev commented on _includes/payment-order-other-features.md
> +[swedbankpay-logo-payment]: /assets/screenshots/logourl/logourl-swedbank.png
Codacy found an issue: [[no-unused-definitions] Found unused definition](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6039190)

2020-08-27 10:04 UTC, merged