Feature/add merchant logo
SwedbankPay/developer.swedbankpay.com pull request #653
Opened 2020-09-04 12:41 UTC by Xillians

Added a svg file that can be then used as a custom merchant logo. Its main purpose is to send in as "logoUrl", giving a logo that can be re-used for e.g. documentation / testing. Original image was found on [thenounproject](https://thenounproject.com/browse/?i=3437061).

2020-09-04 12:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SwedbankPay/developer.swedbankpay.com?pullRequest=653) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SwedbankPay/developer.swedbankpay.com?pullRequest=653) before we can accept your contribution.<br/><hr/>**Syver** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SwedbankPay/developer.swedbankpay.com?pullRequest=653) it.</sub>

2020-09-07 08:48 UTC, asbjornu requested changes
Can you please rename `customMerchantLogo.svg` to `merchant_logo.svg`? Also, if we have a suitable name for the merchant, we should use that as the name of the logo file instead.

2020-09-07 09:10 UTC, Xillians commented
> Can you please rename `customMerchantLogo.svg` to `merchant_logo.svg`? Also, if we have a suitable name for the merchant, we should use that as the name of the logo file instead.

name has been updated to merchant_logo as there was no name decisive name as of yet.

2020-09-07 09:14 UTC, asbjornu approved these changes

2020-09-07 09:15 UTC, asbjornu commented
@SwedbankPay/techwriters, you're free to merge this whenever you're ready to start using the new logo in screenshots.

2020-09-08 07:53 UTC, merged