dx-1205 changed the sequence of the overall main meny
SwedbankPay/developer.swedbankpay.com pull request #677
Opened 2020-09-15 11:43 UTC by marinafrydenb

2020-09-15 11:46 UTC, asbjornu approved these changes
If this works, then okay, but the field should really have been named **`menu_order`**, not `menu-order`. I think we should change this before we go live with the new design.

2020-09-16 08:41 UTC, arebra reviewed
Where is the menu_order change?

2020-09-16 11:01 UTC, asbjornu commented
> Where is the menu_order change?

@arebra, in #679. :)

2020-09-16 11:03 UTC, arebra approved these changes

2020-09-17 08:00 UTC, asbjornu requested changes

2020-09-17 08:00 UTC, asbjornu commented on Gemfile
> +gem 'swedbank-pay-design-guide-jekyll-theme', '~> 1.8'
1.8.1 brings in the `menu_order` renaming.

```suggestion
gem 'swedbank-pay-design-guide-jekyll-theme', '~> 1.8.1'
```

2020-09-17 10:54 UTC, asbjornu commented
Superseded by #679.

2020-09-17 10:54 UTC, closed without merging