dx-1207 changes to config with new kramdown
SwedbankPay/developer.swedbankpay.com pull request #679
Opened 2020-09-15 13:39 UTC by marinafrydenb

2020-09-15 13:49 UTC, asbjornu requested changes
You seem to be missing quite a few `code-header` replacements?

2020-09-15 13:49 UTC, asbjornu commented on _config.yml
> +        start_line: 1
These should all be less indented.

```suggestion
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    guess_lang: true
    default_lang: html
    css_class: "code-view"
    code_class: "code-view-code"
    table_class: "code-view-table"
    gutter_class: "code-view-numbers"
    block:
      line_numbers: true
      start_line: 1
```

2020-09-15 14:11 UTC, asbjornu requested changes

2020-09-15 14:11 UTC, asbjornu commented on index.md
>  front_page: true
```suggestion
```

2020-09-16 09:27 UTC, payex-dev commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 5
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6182398&bid=20178598)

2020-09-16 09:27 UTC, payex-dev commented on _includes/moto.md
> +{:.code-view-header}
Codacy found an issue: [[list-item-bullet-indent] Incorrect indentation before bullet: remove 2 spaces](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6182398)

2020-09-16 09:27 UTC, payex-dev commented on _includes/moto.md
> +
Codacy found an issue: [[list-item-bullet-indent] Incorrect indentation before bullet: remove 2 spaces](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6182398)

2020-09-16 09:27 UTC, payex-dev commented on _includes/moto.md
> +```http
Codacy found an issue: [[list-item-bullet-indent] Incorrect indentation before bullet: remove 2 spaces](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6182398)

2020-09-16 09:28 UTC, payex-dev commented on _includes/moto.md
> +
Codacy found an issue: [Command failed: git rev-parse --show-cdup
/bin/sh: git: not found
](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6182398)

2020-09-16 09:28 UTC, payex-dev commented on _includes/moto.md
> +**Request**
Codacy found an issue: [[list-item-bullet-indent] Incorrect indentation before bullet: remove 2 spaces](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6182398)

2020-09-16 09:32 UTC, payex-dev commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 5
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6182398&bid=20178598)

2020-09-16 09:32 UTC, payex-dev commented on _includes/moto.md
> +
Codacy found an issue: [[list-item-bullet-indent] Incorrect indentation before bullet: remove 2 spaces](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6182398)

2020-09-16 09:32 UTC, payex-dev commented on _includes/moto.md
> +**Request**
Codacy found an issue: [[list-item-bullet-indent] Incorrect indentation before bullet: remove 2 spaces](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6182398)

2020-09-16 09:32 UTC, payex-dev commented on _includes/moto.md
> +{:.code-view-header}
Codacy found an issue: [[list-item-bullet-indent] Incorrect indentation before bullet: remove 2 spaces](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6182398)

2020-09-16 09:32 UTC, payex-dev commented on _includes/moto.md
> +
Codacy found an issue: [Command failed: git rev-parse --show-cdup
/bin/sh: git: not found
](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6182398)

2020-09-16 09:32 UTC, payex-dev commented on _includes/moto.md
> +```http
Codacy found an issue: [[list-item-bullet-indent] Incorrect indentation before bullet: remove 2 spaces](https://app.codacy.com/gh/SwedbankPay/developer.swedbankpay.com/pullRequest?prid=6182398)

2020-09-16 10:52 UTC, asbjornu requested changes
Shouldn't theme be upgraded to version 1.8 in this PR as well? Or has that been done in a previous PR already?

2020-09-16 10:52 UTC, asbjornu commented on _includes/moto.md
> +## MOTO
Why is `moto.md` added in this PR? Doesn't it belong to #671?

2020-09-16 14:17 UTC, NullableInt approved these changes
LGTM

2020-09-16 20:41 UTC, asbjornu requested changes
Why isn't theme upgraded to version 1.8 like in #680?

2020-09-17 07:55 UTC, asbjornu requested changes

2020-09-17 07:55 UTC, asbjornu commented on index.md
> +layout: front_page
The name of the layout is `front-page`.

```suggestion
layout: front-page
```

2020-09-17 10:48 UTC, asbjornu approved these changes
🎉

2020-09-17 10:53 UTC, merged