Feature/dx 1234 correct typos dev portal
SwedbankPay/developer.swedbankpay.com pull request #704
Opened 2020-10-06 12:22 UTC by marinafrydenb

2020-10-06 21:26 UTC, asbjornu requested changes

2020-10-06 21:26 UTC, asbjornu commented on payment-instruments/invoice/seamless-view.md
> +<html language="javascript">
```suggestion
<script language="javascript">
```

2020-10-06 21:26 UTC, asbjornu commented on payment-instruments/invoice/seamless-view.md
> +</html>
```suggestion
</script>
```

2020-10-06 21:26 UTC, asbjornu commented on resources/public-migration-key.md
> +mQINBF46XsgBEACh1Yz2neopGj1UdGC+jDW+Cspq126X58EK1tWdo6mv3wpzN5GB
Why is the key changed?

2020-10-07 10:51 UTC, marinafrydenb commented on resources/public-migration-key.md
> +mQINBF46XsgBEACh1Yz2neopGj1UdGC+jDW+Cspq126X58EK1tWdo6mv3wpzN5GB
Mistake! this is now corrected.

2020-10-07 19:47 UTC, arebra approved these changes
Great!

2020-10-07 22:50 UTC, asbjornu requested changes

2020-10-07 22:50 UTC, asbjornu commented on _includes/payment-resource.md
> +```json
```suggestion
```http
```

2020-10-07 22:50 UTC, asbjornu commented on resources/public-migration-key.md
> -```pgp
No code fence? How does this look then?

2020-10-08 08:15 UTC, marinafrydenb commented on _includes/payment-resource.md
> +```json
fixed!

2020-10-08 08:15 UTC, marinafrydenb commented on resources/public-migration-key.md
> -```pgp
Fixed!

2020-10-08 10:56 UTC, asbjornu approved these changes
🎉 ❤️

2020-10-08 12:16 UTC, merged