dx-1242 Fixed the PATCH code example
SwedbankPay/developer.swedbankpay.com pull request #708
Opened 2020-10-08 13:10 UTC by arebra

2020-10-08 13:18 UTC, asbjornu requested changes
I think it's wise to avoid “smart quotes” in code.

2020-10-08 13:18 UTC, asbjornu commented on _includes/delete-token.md
> +PATCH /psp/{{ api_resource }}/{% if api_resource == “paymentorders” %}recurrenceTokens/{{ page.payment_token }} HTTP/1.1 {% else %}payments/instrumentData/{{ page.payment_token }} HTTP/1.1 {% endif %
```suggestion
PATCH /psp/{{ api_resource }}/{% if api_resource == "paymentorders" %}recurrenceTokens/{{ page.payment_token }} HTTP/1.1 {% else %}payments/instrumentData/{{ page.payment_token }} HTTP/1.1 {% endif %}
```

2020-10-08 13:18 UTC, asbjornu commented on _includes/delete-token.md
> +  “tokenType” : “{{ token_field_name }}“{% endif %}
```suggestion
  "state": "Deleted",
  "comment": "Comment on why the deletion is happening"{% if documentation_section == "card" %},
  "tokenType" : "{{ token_field_name }}"{% endif %}
```

2020-10-08 13:56 UTC, asbjornu requested changes
The URLl building becomes easier to understand if we do it outside of the code example.

2020-10-08 13:56 UTC, asbjornu commented on _includes/delete-token.md
```suggestion
{% capture patch_url %}
    /psp/{{ api_resource }}/
    {% if api_resource == "paymentorders" %}
        recurrenceTokens
    {% else %}
        payments/instrumentData
    {% endif %}
    /{{ page.payment_token }}
{% endcapture %}
{% assign patch_url=patch_url | strip_newlines %}

```

2020-10-12 13:05 UTC, asbjornu requested changes
I made a few changes. Please take a peek at 1dd543858c79d10b2a7d26673d79881ff5535653 where I describe the changes I made and why.

Left to do now is to ensure that `delete-token.md` is only included once in Other Features. I think it's repeated 3 times underneath Card, for instance. Its inclusion in `card-purchase.md` doesn't seem to make much sense, for instance.

2020-10-16 21:27 UTC, asbjornu commented
https://github.com/SwedbankPay/developer.swedbankpay.com/pull/708#pullrequestreview-506601232 still needs some followup, no?

2020-10-20 22:23 UTC, arebra commented
Is there anything I can do with #708? I can't approve the review of my own task? Or am I missing something?

2020-10-21 00:07 UTC, asbjornu commented
I still can't see that the following has been done? The last commit in this PR was made by me, so I don't understand where you've removed the include duplicates, @arebra?

> Left to do now is to ensure that `delete-token.md` is only included once in Other Features. I think it's repeated 3 times underneath Card, for instance. Its inclusion in `card-purchase.md` doesn't seem to make much sense, for instance.

2020-10-21 10:26 UTC, arebra commented
That's odd, but I guess I didn't commit and push it correctly then. I'll fix it :)

2020-10-22 09:36 UTC, asbjornu approved these changes

2020-10-22 09:58 UTC, merged