DX-1490 Fix externalNonPaymentToken
SwedbankPay/developer.swedbankpay.com pull request #832
Opened 2021-02-09 23:27 UTC by arebra

Removed SL from the description of ExternalNonPaymentToken and did some textual garden work elsewhere.

2021-02-10 01:33 UTC, asbjornu requested changes
I think it's unwise to do any changes at all to `develop` until #828 is completed and merged. If this change is supposed to get into production anytime soon, I suggest closing this PR and recreating it from `master` as a `hotfix`.

2021-02-10 12:03 UTC, arebra commented
Hard to disagree on that one :) Hopefully this will be mergeable when checkout is done.

2021-03-02 11:13 UTC, arebra commented
I updated this task with the most recent develop. OK to merge, @asbjornu ?

2021-03-02 11:36 UTC, asbjornu approved these changes

2021-03-02 12:07 UTC, merged