Bump theme to version 1.9.10
SwedbankPay/developer.swedbankpay.com pull request #835
Opened 2021-02-11 14:30 UTC by PhungNg

Fixed horizontal scrollbar

2021-02-11 16:52 UTC, asbjornu approved these changes

2021-02-12 06:09 UTC, NullableInt requested changes
Don't add a dependency on `x64-mingw32`
Also this removes `jekyll-assets`, don't we use that?
See #836 to see an automated version of this

2021-02-12 09:16 UTC, asbjornu commented
> Don't add a dependency on `x64-mingw32`

It seems to be required for Windows, so we might as well just add it?

> Also this removes `jekyll-assets`, don't we use that?

No, it doesn't seem like we are. I asked @PhungNg to remove it in order to get `bundle update` to work.

> See #836 to see an automated version of this

#836 merges into `develop`, we need this in `master` so we don't have to wait for `develop` to become stable and release ready.

2021-02-12 09:32 UTC, NullableInt approved these changes

2021-02-12 14:09 UTC, merged