DX-1510: Updated IP address
SwedbankPay/developer.swedbankpay.com pull request #851
Opened 2021-03-02 11:18 UTC by arebra

2021-03-02 11:22 UTC, trieutran91 approved these changes

2021-03-02 11:55 UTC, asbjornu requested changes
We need to figure out how to roll this change out since it seems like the IP address is going to be different between External Integration and production between March 23. and May 25.

2021-03-22 11:11 UTC, asbjornu commented on _includes/alert-ip-address.md
> +the <strong>test environment</strong> and from `82.115.146.1` in the
```suggestion
the <strong>external integration environment</strong> and from `82.115.146.1` in the
```

2021-03-22 11:16 UTC, asbjornu commented on _includes/alert-ip-address.md
> +the <strong>test environment</strong> and from `82.115.146.1` in the
Sorry, I can see that we call "external integration" for "test environment". Ignore this.

2021-03-22 11:16 UTC, asbjornu approved these changes

2021-03-22 11:54 UTC, merged