DX-1530: Removed instrument from checkout and added disablePaymentMenu
SwedbankPay/developer.swedbankpay.com pull request #896
Opened 2021-03-30 23:09 UTC by arebra

Tried to fix the table, and it works without the if. When the if is added everything goes down the drain. Please help?

2021-03-30 23:10 UTC, arebra commented
I see two dashes are added to the if and endif. That was the final attempt at fixing it. It used to be dash at the end only.

2021-04-06 13:07 UTC, asbjornu requested changes
Looks good except HTMLProofer complaining about this:

```
- /srv/jekyll/_site/checkout/v2/payment-menu.html
  *  internally linking to /checkout/v2/features/optional/instrument-mode, which does not exist (line 4708)
     <a href="/checkout/v2/features/optional/instrument-mode">Instrument Mode</a>
```

That failure looks unrelated to this PR, but should still be fixed, I suppose.

2021-04-06 15:52 UTC, arebra commented
I'll fix that, but @trieutran91 says he has trouble getting it to look good using localhost.

2021-04-08 13:59 UTC, asbjornu approved these changes

2021-04-08 14:33 UTC, merged